package com.plat.acoal.model;

import java.util.Date;

public class AccessToken {

    // 凭证有效时间，单位：秒
    private int expiresin;

    public int getExpiresin() {
        return expiresin;
    }

    public void setExpiresin(int expiresin) {
        this.expiresin = expiresin;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column t_accesstoken.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column t_accesstoken.accesstoken
     *
     * @mbggenerated
     */
    private String accesstoken;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column t_accesstoken.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column t_accesstoken.ID
     *
     * @return the value of t_accesstoken.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column t_accesstoken.ID
     *
     * @param id
     *            the value for t_accesstoken.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column t_accesstoken.accesstoken
     *
     * @return the value of t_accesstoken.accesstoken
     *
     * @mbggenerated
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column t_accesstoken.accesstoken
     *
     * @param accesstoken
     *            the value for t_accesstoken.accesstoken
     *
     * @mbggenerated
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken == null ? null : accesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column t_accesstoken.updatetime
     *
     * @return the value of t_accesstoken.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column t_accesstoken.updatetime
     *
     * @param updatetime
     *            the value for t_accesstoken.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}
